# Generated by Django 4.2.3 on 2023-07-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jhpl_ims", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doc_controller",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="doc_controller",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="jhpl_ims_masterlist",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="jhpl_ims_masterlist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="notes",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="notes",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
