# Generated by Django 4.2.3 on 2023-07-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jhpl_ims", "0003_alter_jhpl_ims_masterlist_approved_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jhpl_ims_masterlist",
            name="doc_num",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="jhpl_ims_masterlist",
            name="rev_num",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
