# Generated by Django 4.2.3 on 2023-07-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jhpl_ims", "0004_alter_jhpl_ims_masterlist_doc_num_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jhpl_ims_masterlist",
            name="status",
        ),
    ]
