# Generated by Django 4.2.3 on 2023-07-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jhpl_ims", "0006_jhpl_ims_masterlist_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jhpl_ims_masterlist",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Obsolete", "Obsolete")], max_length=8
            ),
        ),
    ]
