# Generated by Django 4.2.3 on 2023-07-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jhpl_ims", "0007_alter_jhpl_ims_masterlist_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jhpl_ims_masterlist",
            name="approved_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="jhpl_ims_masterlist",
            name="issue_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="jhpl_ims_masterlist",
            name="reviewed_date",
            field=models.DateField(),
        ),
    ]
