# Generated by Django 4.2.3 on 2023-07-25 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jhpl_ims", "0010_alter_jhpl_ims_masterlist_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jhpl_ims_masterlist",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jhpl_approved_by",
                to="jhpl_ims.doc_controller",
            ),
        ),
        migrations.AlterField(
            model_name="jhpl_ims_masterlist",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jhpl_reviewed_by",
                to="jhpl_ims.doc_controller",
            ),
        ),
    ]
